// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"RetryBattle","status":false,"description":"RetryBattlePlugin","parameters":{"RetryNormalEnemy":"ON","RetryBossEnemy":"ON","CommandRetry":"リトライ","CommandLoad":"ロード","CommandTitle":"タイトルへ","WindowY":"464","ShowMenu":"ON","Message":"\\c[2]あなたは死にました。\\c[0]","MessageY":"360","FontSize":"32"}},
{"name":"SimpleMsgSideView","status":false,"description":"at sideview battle, only display item/skill names.","parameters":{"displayAttack":"0","position":"1"}},
{"name":"WeaponSkill","status":true,"description":"Change skill id of attack for each weapon.","parameters":{}}
];
